### ISSUE TITLE
[Agenda] The upper table header is confusing

### ISSUE THREAD

**Issue by uda** [Hamakor/AugustPenguin#136]
I think the morning / afternoon headers should be separate and shown in relevance

**Comment by tomer** [comment]
I think we can set the headers as sticky.

**Comment by uda** [comment]
That's beside the point, I am referring to the double row of morning / afternoon tracks.

![2017-08-23_13-01-22_001](https://user-images.githubusercontent.com/199314/29612583-a29e67fe-880a-11e7-8310-6044cb6938f0.png)

I will make a PR with my suggestion later.

**Comment by tbrisker** [comment]
I think this was solved in 104505e9170a0f07ac2aafe86cf0b6fb78f959c2. closing.
