### ISSUE TITLE
[question] what kind of changes can I suggest for the schedule / תכנייה?

### ISSUE THREAD

**Issue by OriHoch** [Hamakor/AugustPenguin#145]
* currently it just shows the title, is there a plan to include descriptions as well?
* in PR #144 I added some links - is that ok? If you don't plan to show descriptions, can I add a link from the presentation title to a personal page showing details about the presentation?

**Comment by tbrisker** [comment]
@OriHoch Thanks for the input, we are planning to link from the agenda to the talk descriptions, from which you could link later to the relevant pages.

**Comment by OriHoch** [comment]
thanks
