### ISSUE TITLE
[ap2015] Add QR code

### ISSUE THREAD

**Issue by tomer** [Hamakor/AugustPenguin#38]
@shaib suggested to place QR code on the site, which will link to the site and/or directions. 

We can do almost everything, but there are no requirements. What would we need on the code, and where should we place it?

**Comment by tomer** [comment]
# Geo location

![Geo location](http://zxing.org/w/chart?cht=qr&chs=350x350&chld=L&choe=UTF-8&chl=geo%3A32.0897%2C34.802373%3Fq%3D32.0897%2C34.802373)

# website

![website](http://zxing.org/w/chart?cht=qr&chs=350x350&chld=L&choe=UTF-8&chl=http%3A%2F%2Fap.hamakor.org.il)

# Calender event

![calender event](http://zxing.org/w/chart?cht=qr&chs=350x350&chld=L&choe=UTF-8&chl=BEGIN%3AVEVENT%0D%0ASUMMARY%3A%D7%90%D7%95%D7%92%D7%95%D7%A1%D7%98+%D7%A4%D7%99%D7%A0%D7%92%D7%95%D7%95%D7%99%D7%9F+2015%0D%0ADTSTART%3A20150807T053000Z%0D%0ADTEND%3A20150807T110000Z%0D%0ALOCATION%3A%D7%91%D7%A0%D7%99%D7%99%D7%9F+%D7%9E%D7%99%D7%98%D7%A9%D7%9C+%28%D7%94%D7%91%D7%A0%D7%99%D7%99%D7%9F+%D7%94%D7%97%D7%93%D7%A9%29%2C+%D7%9E%D7%9B%D7%9C%D7%9C%D7%AA+%D7%A9%D7%A0%D7%A7%D7%A8+-+%D7%91%D7%99%D7%B4%D7%A1+%D7%92%D7%91%D7%95%D7%94+%D7%9C%D7%94%D7%A0%D7%93%D7%A1%D7%94+%D7%95%D7%9C%D7%A2%D7%99%D7%A6%D7%95%D7%91%2C+%D7%A8%D7%9E%D7%AA+%D7%92%D7%9F%0D%0AEND%3AVEVENT%0D%0A)

**Comment by shaib** [comment]
all three work for me, please add them to the site.

**Comment by tomer** [comment]
I am not sure if it'd be useful to have as many QRs as possible.

**Comment by tbrisker** [comment]
AP2015 site is no longer actively maintained, you are welcome to open a PR to update it. Closing this issue.
