### ISSUE TITLE
[ap2015] oVirt session notes

### ISSUE THREAD

**Issue by tomer** [Hamakor/AugustPenguin#51]
A [tweet](https://twitter.com/mureinik/status/629683488103378945) by @mureinik informs us that the slides are available [here](http://www.slideshare.net/AllonMureinik/introduction-to-ovirtaugustpenguin2015).

@tbrisker has [tweeted](https://twitter.com/tbrisker_pro/status/629601062702350336) a photo, and so it [@mureinik](https://twitter.com/mureinik/status/629589590756622336).

**Comment by mureinik** [comment]
I'm waiting for an email from the organizers about upload details. Once I have them, I'll upload my slides and screen capture.

**Comment by tbrisker** [comment]
AP2015 site is no longer actively maintained, you are welcome to open a PR to update it. Closing this issue.
