### ISSUE TITLE
[ap2015] Shell session notes

### ISSUE THREAD

**Issue by tomer** [Hamakor/AugustPenguin#52]
A [tweet](https://twitter.com/sh_yaron/status/629585185399410688) by @yarons has a photo of the lecture.

**Comment by tbrisker** [comment]
AP2015 site is no longer actively maintained, you are welcome to open a PR to update it. Closing this issue.

**Comment by tbrisker** [comment]
AP2015 site is no longer actively maintained, you are welcome to open a PR to update it. Closing this issue.
