### ISSUE TITLE
[ap2015] systemd session notes

### ISSUE THREAD

**Issue by tomer** [Hamakor/AugustPenguin#53]
@doron-fediuck has tweeted [multiple photos](https://twitter.com/doron_f/status/629544267241779200).

@tbrisker has tweeted one more [photo](https://twitter.com/tbrisker_pro/status/629537670864048133).

**Comment by tomer** [comment]
@ik5 has published [some photos](https://www.facebook.com/idkn5/posts/10153581941413383) on Facebook.

**Comment by tbrisker** [comment]
AP2015 site is no longer actively maintained, you are welcome to open a PR to update it. Closing this issue.
