### ISSUE TITLE
[ap2016] Previous years list is inconsistent

### ISSUE THREAD

**Issue by uda** [Hamakor/AugustPenguin#88]
The list shows numbers 1-5 and then 2007-2015? is there a reason or can I PR a consistent layout?

**Comment by tbrisker** [comment]
The reason is that those were the event titles, but I don't object to standardizing. If people click one then they will see the original title. If you're touching on this, might want to make the list a drop-down from the menu instead of just a list at the tail.

**Comment by tbrisker** [comment]
AP2016 site is no longer actively maintained, you are welcome to open a PR to update it. Closing this issue.
