### ISSUE TITLE
[ap2016] Can we use a better HTML5 layout?

### ISSUE THREAD

**Issue by uda** [Hamakor/AugustPenguin#89]
Currently the layout is mainly a stream of divs, I think it would be better to use semantic tags and sections, which will make coding and styling easier.

**Comment by tbrisker** [comment]
PRs are welcome

**Comment by uda** [comment]
OK, I will do it, but please check PR #47, my work might conflict with it.

**Comment by tbrisker** [comment]
@uda don't worry about it, it is against the ap2015 branch

**Comment by uda** [comment]
Correct, missed that.

**Comment by tbrisker** [comment]
AP2015 site is no longer actively maintained, you are welcome to open a PR to update it. Closing this issue.
